### ISSUE TITLE
Setting in ACP to remove the Subject input box completely.

### ISSUE THREAD

**Issue by ivanovd** [BoardTools/QuickReply#16]
Hi,

Could you please add a setting that will remove the Subject from the Quick Reply box? It just takes up space. You know what you are replying to anyway.

Thanks

**Comment by Galixte** [comment]
@lavigor could you take a look ?

**Comment by lavigor** [comment]
@Galixte, this feature is planned and will be done soon.

**Comment by lavigor** [comment]
Implemented in 239d7017272ba313087527111dabca3b3155703f.
