### ISSUE TITLE
Ajax Posting doesn't work at all

### ISSUE THREAD

**Issue by Sarr** [BoardTools/QuickReply#40]
Hi there. Ajax Posting is making a notice about "Ajax error" when you post and nothing happens. Preview and everything else seems to work fine though.
Plus, the post is added, just the page is not updated. So I needed to disable this function.
Can you please look into this issue? You can find me here: http://forum.swordcoast.pl/

**Comment by lavigor** [comment]
@Sarr, you have SEO extension installed, have you followed [the instructions in the FAQ](https://github.com/Tatiana5/QuickReply/wiki#can-this-extension-work-together-with-phpbb-seo-ultimate-seo-url)?

**Comment by lavigor** [comment]
If you have any more questions, you can ask them here.
The issue is considered closed.

**Comment by Sarr** [comment]
Hello, I've seen it, but I don't use PHPBBSEO. I use most popular SEO for PHBBB these days, check it out here:
https://tas2580.net/downloads/phpbb-seo-url/
https://github.com/tas2580/seourls
https://tas2580.net/

So your advice can't help me, it's much more simple extension but does work nicely otherwise.

**Comment by lavigor** [comment]
> most popular SEO for PHBBB

Maybe it's popular somewhere, but you are the first who told about the bug.

You just needed to write the name of the extension. I'll try to make the fixes for it soon. ;-)

**Comment by Sarr** [comment]
> I'll try to make the fixes for it soon. ;-)
Wow, that's great, big thanks :). If you need any testing at specific configuration, contact me at http://forum.swordcoast.pl

**Comment by BlackSkorpio** [comment]
> Hi there. Ajax Posting is making a notice about "Ajax error" when you post and nothing happens. Preview and everything else seems to work fine though.
> Plus, the post is added, just the page is not updated. So I needed to disable this function.
We are seeing the same over at [Koken Community Support](http://kokensupport.com) to.

AJAX is not reloading the topic after a quick reply is done.
Post is posted though, but you need to manually reload the page to see the new reply

**Comment by eninja** [comment]
I have the same errors with ajax. 

can i disable ajax?

**Comment by lavigor** [comment]
Please do not post in this topic unless you have the mentioned SEO extension installed.
Read [FAQ](https://github.com/BoardTools/QuickReply/wiki) to eliminate incompatibilities with other extensions and styles.
