### ISSUE TITLE
Module mode title

### ISSUE THREAD

**Issue by Galixte** [BoardTools/QuickReply#41]
Hi @Tatiana5  @lavigor,

the title of the module mode sould be: https://github.com/Tatiana5/QuickReply/blob/master/acp/quickreply_info.php#L21 ```ACP_QUICKREPLY``` instead of ```ACP_QR_CONFIG```, no ?

**Comment by lavigor** [comment]
No. The title is OK.

**Comment by Galixte** [comment]
Are you sure? It's not translated in modules list, and all extensions have a module title translated, because it use a same title of in EXTENSIONS tab in ACP.

**Comment by lavigor** [comment]
OK. I think that it should be translatable.
I'll decide about the variable soon after adding new changes for the next release.
Thank you. ;-)

**Comment by Galixte** [comment]
Thanks to you ;)

**Comment by lavigor** [comment]
Fixed in 4e9ab3ec8aa2cb2495b50e7419badbb59462b7c0.
