### ISSUE TITLE
Dropdrown problem

### ISSUE THREAD

**Issue by ricardorohde** [BoardTools/QuickReply#43]
the dropdown of "Insert quote in the Quick Reply form" don't work at my style "mobbern"

**Comment by lavigor** [comment]
This style is not supported by me, but there're users that use this style.
I do not plan to include the support for the mentioned paid style, but you can follow [this link](http://cabinetadmina.ru/viewtopic.php?p=69496#p69496) that may help you (note: content is in Russian).
Note the archives, Google Translate may help you to read other replies.
Or you can ask me if you want to translate something. :)

**Comment by ricardorohde** [comment]
nice! thats works! thanks!
