### ISSUE TITLE
Add support for ComBoot style

### ISSUE THREAD

**Issue by lavigor** [BoardTools/QuickReply#46]
Adjust all features of QuickReply extension for ComBoot 3.1.

**Comment by lavigor** [comment]
Support for ComBoot was added to the `develop` branch of this repository.

@TheZoker, it will be very nice if you can check whether this extension works with your style. :wink:

**Comment by TheZoker** [comment]
@lavigor Will check it as soon as possible :)

**Comment by TheZoker** [comment]
Everything seems to work so far :smile: 
Execpt for the ajax post title. It has "display: none" attr after posting:
![img_2016 02 08_15h32m37s_026_](https://cloud.githubusercontent.com/assets/1368405/12888238/5c9bd788-ce79-11e5-9ec8-4d623c1b0e14.png)

**Comment by lavigor** [comment]
@TheZoker missing titles is a feature. ;D
Called `Show posts subjects in topics` in settings.
I wonder if it should be implemented here at all, but I didn't remove the title entirely.
If I remove the whole title block, it looks OK except for the top right corner.

Do not know about closing the panel as I prefer when it is always opened.
But if this is the idea of the style, I can do that. =)

**Comment by TheZoker** [comment]
@lavigor Just give the `panel-heading` element a `display: none`:
![img_2016 02 08_17h51m39s_027_](https://cloud.githubusercontent.com/assets/1368405/12892521/e5a7c588-ce8c-11e5-9318-eb5da1195112.png)

I guess if the user posted a response, he doesn't need the quick response element anymore, so for me it would be more intuitive to close it :smile:

**Comment by lavigor** [comment]
Fixed!

**Comment by TheZoker** [comment]
Everything seems to work now :)
I added your ext to the compatibility pack page:
https://comboot.io/compatibility/
If you have any suggestions for this page, let me know!

**Comment by lavigor** [comment]
OK. Thank you!
