### ISSUE TITLE
phpBB 3.2.0-b1 compatibility issues

### ISSUE THREAD

**Issue by C1n** [BoardTools/QuickReply#54]
Fresh install 3.2.0-b1, php7, when visiting a topic:

Fatal error: Uncaught Error: Call to undefined method parse_message::set_mimetype_guesser() in .../phpBB/ext/boardtools/quickreply/event/listener_helper.php:212 Stack trace: #0 .../phpBB/ext/boardtools/quickreply/event/listener.php(265): boardtools\quickreply\event\listener_helper->handle_attachments(21, '2142', true) #1 [internal function]: boardtools\quickreply\event\listener->viewtopic_modify_data(Object(phpbb\event\data), 'core.viewtopic_...', Object(phpbb\event\dispatcher)) #2 .../phpBB/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(phpbb\event\data), 'core.viewtopic_...', Object(phpbb\event\dispatcher)) #3 .../phpBB/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'core.viewtopic_...', Object(phpbb\ev in .../phpBB/ext/boardtools/quickreply/event/listener_helper.php on line 212

**Comment by lavigor** [comment]
I haven't started making edits for 3.2.0 yet.
Bit I'll do them soon.
