### ISSUE TITLE
Time for a single scroll and animation event: Not working

### ISSUE THREAD

**Issue by tatari2909** [BoardTools/QuickReply#57]
Today, I tried to install this extension for my forum (phpbb 3.1.9).

I set-up the option "Time for a single scroll and animation event:" to zero. But when user click on a topic, the cursor move to quick reply form immediately. (You can see my demo at http://discourse.phen.biz/

Many thanks.

**Comment by lavigor** [comment]
@tatari2909 does this happen only when QuickReply extension is enabled?
The mentioned setting is not related to moving the cursor.
Maybe you have some other scripts for that?

**Comment by tatari2909** [comment]
hi @lavigor , yup when I enable extension "QuickReply Reloaded	1.0.2-dev" this issue happen, see my record

http://www.youtube.com/embed/y_Q7IZtyjVE?vq=hd1080

Many thanks

**Comment by lavigor** [comment]
@tatari2909 OK, could you please give me a test account and enable the extension so that I can test this issue?

**Comment by tatari2909** [comment]
@lavigor , okie, my account:
name: sam
Passs: 123456#

Url: http://diendan.phen.biz

Many thank.
ah, one more question, I'd like to add an button to phpbb3 editor:

http://i.imgur.com/Leu7eRT.png

I edit posting_buttons.html file as below topic
https://github.com/Korchy/phpbb_imgur

But it not efffect. Can you help me about this?

**Comment by tatari2909** [comment]
I see that, this extension replace original editor and I can not understand why I had disable this extension, I still can enable it on Board Feature setting

> Allow quick reply:
This switch allows for the quick reply to be disabled board-wide. When enabled, forum specific settings will be used to determine whether the quick reply is displayed in individual forums.

If I enable this option. quick reply will show without bbcode bar. and I tried to change anything from file posting_buttons.html will not effect.
