### ISSUE TITLE
Develop branch not compatible with ComBoot-3.1-1.1-rc3

### ISSUE THREAD

**Issue by ravand1990** [BoardTools/QuickReply#59]
Can you confirm this? Updated comboot and everything stoped working.

**Comment by lavigor** [comment]
@ravand1990 no, I cannot confirm this.
Tested right now the latest development versions of QuickReply and ComBoot.

**Comment by ravand1990** [comment]
yes you are right, i had the problem again that the folder had to be called "ComBoot" and nothing else :/ my bad

**Comment by lavigor** [comment]
> how is the update going :)?

I plan to release the first beta this week.
I hope to resolve some small issues soon.
