### ISSUE TITLE
Installed, not working

### ISSUE THREAD

**Issue by kleuter** [BoardTools/QuickReply#62]
Installed on a clean phpbb 3.1.9, prosilver, not working. Default options

I see only these in the page source:
```
<link href="./ext/boardtools/quickreply/styles/prosilver/theme/quickreply.css?assets_version=3" rel="stylesheet" type="text/css" media="screen" />

//<![CDATA[
var quickreply = {};

// Special features for QuickReply - settings.
quickreply.special = {
	hideSubject: true};

// Special features for QuickReply - functions.
quickreply.special.functions = {};
//]]>
</script>

<script type="text/javascript" src="./ext/boardtools/quickreply/styles/prosilver/template/quickreply_special.js?assets_version=3"></script>
```

**Comment by lavigor** [comment]
Standard quick reply should be enabled in the certain forum.

**Comment by kleuter** [comment]
standard quick reply for 3.0 was deleted after migrating to 3.1

**Comment by lavigor** [comment]
@kleuter sorry for the late reply, but your issue does not seem to be related to the extension itself.
This extension does not affect the saving process for existing ACP settings.
