### ISSUE TITLE
Notification not working on phpBB 3.2.0-RC1

### ISSUE THREAD

**Issue by C1n** [BoardTools/QuickReply#63]
Hi there,

I was testing the develop 2.0 version and everything works perfectly but when I refer a username, that user doesn't receive a notification although it is enabled in their preferences.

The "boardtools.quickreply.notification.type.quicknick" is added to the "phpbb_notification_types" table, but no notifications are added to the "phpbb_notifications" table.

**Comment by lavigor** [comment]
Hello, @C1n.
Thank you for your reply.
We have not adapted notifications for phpBB 3.2 yet.

That branch is currently work-in-progress, there have been no beta releases yet.

**Comment by lavigor** [comment]
I'll close this issue when we make the changes.

**Comment by onlyproevo** [comment]
How are you getting on with the version for phpBB 3.2?

**Comment by traims** [comment]
Thank you for the extension! We'd really appreciate an adaptation for 3.2.

**Comment by onlyproevo** [comment]
... :(

**Comment by lavigor** [comment]
Fixed in 2.0.0-beta1.
