### ISSUE TITLE
Quote notification not working for 1.1.0-b1

### ISSUE THREAD

**Issue by BioLogIn001** [BoardTools/QuickReply#64]
Hey

With 1.1.0-b1, even if using "quote" button on a previous post, the QR form still uses "reply" parameter for posting $mode. 

Therefore "notification.type.quote" notification never triggers, and users don't get any notifications when quoted.

**Comment by lavigor** [comment]
@BioLogIn001 quote notifications do not depend on the `mode` parameter.
You can also quote people when starting a new topic and they should receive notifications.

Quote notifications work OK in this version.

**Comment by lavigor** [comment]
@BioLogIn001 please note that users will not receive notifications if the setting `Add a link to the profile of the post author when using quick quote` is enabled.
That behaviour will disappear in the version for phpBB 3.2 as it will use the built-in back link feature.

**Comment by BioLogIn001** [comment]
@lavigor 
Thanks for the clarification, this was indeed a matter of settings you mentioned. My apologies.
