### ISSUE TITLE
Swedish language package

### ISSUE THREAD

**Issue by vulcanriders** [BoardTools/QuickReply#65]
Hi!
As I'm building a new website for our association I also adding all the most useful extensions in our upgraded phpBB - among others QuixkReply Reloaded. And now I've made a Swedish language package for this Extensions.

The zip file: [quickreply_sv-language-1_0.zip](https://github.com/vulcanriders/phpBB-and-Extentions/blob/master/language/QuickReply-Reloaded/quickreply_sv-language-1_0.zip)

**Comment by lavigor** [comment]
Hello, @vulcanriders.
Thank you for your translation.

Could you upload it to Transifex and follow the updates that are coming soon please?
[Details about translating this extension.](https://www.phpbb.com/customise/db/extension/quickreply/support/topic/155611)

**Comment by vulcanriders** [comment]
How do I upload the files to Transifex?

I have a trial account on Transifex where I have made the translations. But I do not understand how I can transfer them to you.

And when I try to join on your site on Transifex the Swedish language do not exist there – although I have requested it twice .

 

What do you suggest I should do next?

 

// Tage, @vulcanriders

 

 

 

Från: lavigor [mailto:notifications@github.com] 
Skickat: den 10 november 2016 23:20
Till: BoardTools/QuickReply <QuickReply@noreply.github.com>
Kopia: Tage Strandell <master@vulcanriders-sweden.org>; Mention <mention@noreply.github.com>
Ämne: Re: [BoardTools/QuickReply] Swedish language package (#65)

 

Hello, @vulcanriders <https://github.com/vulcanriders> .
Thank you for your translation.

Could you upload it to Transifex and follow the updates that are coming soon please?
Details about translating this extension. <https://www.phpbb.com/customise/db/extension/quickreply/support/topic/155611>

**Comment by lavigor** [comment]
@vulcanriders you should request Swedish language on Transifex and become its translator. ;)
I have not received such a request yet.

**Comment by lavigor** [comment]
Hmm... I received a notification about your request.
Probably you deleted your request.

**Comment by lavigor** [comment]
Sorry, it is a UI issue of Transifex.
I've added the language, please request becoming its translator.
