### ISSUE TITLE
2.0.0-dev2 QuickNick works for custom groups only

### ISSUE THREAD

**Issue by ivanovd** [BoardTools/QuickReply#67]
Hi, in ver 2.0.0-dev2 QuickNick works only for custom groups, but not for the default group "Registered users"
![maxthonsnap20170203191346](https://cloud.githubusercontent.com/assets/4889583/22600828/eebcd936-ea44-11e6-98d1-2aeb49d8f813.png)
![maxthonsnap20170203191339](https://cloud.githubusercontent.com/assets/4889583/22600829/eebd7b16-ea44-11e6-9952-491d536d1a63.png)

**Comment by Tatiana5** [comment]
This is bug in the phpBB 3.2.0. Identical bbcodes with the sign "=" and without "=" do not work at the same time.

**Comment by ivanovd** [comment]
Thank you very much for the prompt reply Tatiana.

**Comment by lavigor** [comment]
https://tracker.phpbb.com/browse/PHPBB3-14357
Похоже, об этой проблеме особо и не знают.
На оф. сайте похожей информации не нашёл.
