### ISSUE TITLE
ref tag and nicknames

### ISSUE THREAD

**Issue by superfedya** [BoardTools/QuickReply#68]
Hi, 

I use last 2.0 version with phobb 3.2.

ref tag works fine if username have color, like this is working: [ref=#ff6633]username[/ref]
If username doesn't have any color [ref] username[/ref] doesn't works at all. 

Any fix? 

Thanks

**Comment by lavigor** [comment]
@superfedya, there have not been any stable release for version 2.0.
This branch is still in development.

**Comment by onlyproevo** [comment]
@lavigor - are you able to give us an update on the extension's progress? Thanks!

**Comment by lavigor** [comment]
@onlyproevo I didn't forget about this extension and I plan to finish the first beta in June (possibly earlier).

**Comment by onlyproevo** [comment]
@lavigor - thanks for reply. Good luck with the beta! Cannot wait for it! :)

**Comment by lavigor** [comment]
Yes, the release was finally made in June! 😉 
https://boardtools.ru/QuickReply/#v2.0.0-beta1
