### ISSUE TITLE
No QuickQuote dropdown with mobile

### ISSUE THREAD

**Issue by Aurelienazerty** [BoardTools/QuickReply#71]
Hi,

The QuickQuote dropdown is not showing with mobile device.

Tested on : Android 5.1 / Mozilla Firefox mobile 53

**Comment by lavigor** [comment]
What version of QR do you use?

**Comment by Aurelienazerty** [comment]
I used the 2.0.0-dev2 on phpBB  board. I'll try with the 2.0.0-beta1

**Comment by Galixte** [comment]
Lastest here: https://github.com/BoardTools/QuickReply/archive/develop-2.x.zip ;)

**Comment by Aurelienazerty** [comment]
Still the "bug" with the last version _2.0.0-beta1_

**Comment by lavigor** [comment]
There has been a fix for this problem, made in 2.0.0-beta4 and 1.1.0-RC3.
Please reopen if the problem persists.
