### ISSUE TITLE
Notifications for quotes not working.

### ISSUE THREAD

**Issue by spiritatbay** [BoardTools/QuickReply#74]
I've tried every possible setting combination in the ACP. Half the time it disables quotes altogether and the other half it simply won't give a notification when the person is quoted. Enabling/Disabling the app causes the issue to happen/not happen, so it's this latest version causing the problem.

I'm on phpBB3.2, using the latest 2.0.0-beta1.

**Comment by lavigor** [comment]
Hello @spiritatbay!

The best way to test and fix your issue is if you could PM me ([on phpbb.com](https://www.phpbb.com/community/ucp.php?i=pm&mode=compose&u=1406196)) the details of your board where I can test the problem.

**Comment by spiritatbay** [comment]
Done.
