### ISSUE TITLE
Unable to enable ext and unable to delete it's data

### ISSUE THREAD

**Issue by nikolaleon** [BoardTools/QuickReply#75]
I am using rather bigger board. Around 4gb. I am having issues with this ext. I can't enable it it loads forever, it can partially enable it but thats not it. I also can't delete its data, it loads forever. and I have this issue too: https://images-ext-2.discordapp.net/external/9h6hvkrPVFwokQ3cQ8M82Hv7QVu6Zv7YdbOH5X67FiQ/https/i.imgur.com/gTJPJpwr.png

thanks

**Comment by lavigor** [comment]
Hello, @nikolaleon!

I suppose that this is your topic: https://www.phpbb.com/customise/db/extension/quickreply/support/topic/180581.
I've answered you there today, but have not received a reply.

Best regards,
Igor

**Comment by Galixte** [comment]
Maybe sharing a test account on your board: https://pokemon-revolution-online.net/Forum could be improve the investigation.

**Comment by nikolaleon** [comment]
Thing is I can't afford tests on live board. What I can do is to setup a new clone forum in a different directory or have it locally tested via teamviewer
